
#Services
# Postgres, pg admin
#zipkin for tracing
# kafka
# each services -- Patient, Doctor, gateway, config server, kafka
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 22181:2181
    networks:
      - healthsync-network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
#      how many replications we want
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    networks:
      - healthsync-network

#   Postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "Enter your Password"
      POSTGRES_DB: healthsync_db
    ports:
      - "5433:5432"
    networks:
      - healthsync-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

#   Zipkin service for distributed tracing
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - healthsync-network

# Define volumes for db's
volumes:
  postgres-data:

#Network
networks:
  healthsync-network:
    driver: bridge


#  kafka:
#    image: bitnami/kafka:latest
#    container_name: kafka
#    environment:
#      - KAFKA_BROKER_ID=1
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
#      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9092,OUTSIDE://localhost:9092
#      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper
#    ports:
#      - 9092:9092
#    networks:
#      - healthsync-network