spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/doctor
    username: postgres
    password: 'password'
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop


  application:
    name: doctor-service


  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: "ScheduleEventDTO:com.wildy.doctor.kaf.ScheduleEventDTO"
    topic-schedule: doctor-schedule-topic  # Topic name used for the ScheduleEventProducer


#Eureka Config
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082



# Zipkin Config
# default port 9411
management:
  tracing:
    sampling:
      probability: 1.0




