spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/analytics
    username: postgres
    password: "Enter password"
    driver-class-name: org.postgresql.Driver
  jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: create-drop

  application:
    name: analytics


  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: "AppointmentEventDTO:com.wildy.analytics.kaf.payload.AppointmentEventDTO"
    topic-appointment: appointment-events-topic  # Topic name for appointment events

#zipkin
management:
  tracing:
    sampling:
      probability: 1.0
